apiVersion: v1
kind: Pod
metadata:
  name: secure-game
spec:
  containers:
  - name: game-container
    image: rps-game
    imagePullPolicy: Never

    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true

    ports:
    - containerPort: 80

    volumeMounts:
    - name: cache
      mountPath: /var/cache/nginx
    - name: run
      mountPath: /var/run
    - name: log
      mountPath: /var/log/nginx

  volumes:
  - name: cache
    emptyDir: {}

  - name: run
    emptyDir: {}

  - name: log
    emptyDir: {}